# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c3670dcb6ebaac76699ee7cc2ca5ecff8282657fc9691655b22f9e2587dd85d4887db00fdb0abb59f8aaff69c0ecdecbb3ff221bddf21c284b8eaf23570a7f

test:
  secret_key_base: 77f0ce114ca5fd0260565a61f788351f4f53715ae4bac1fd4d8f5ebe7e50efe7e50ad6268e5ac998737597684de10d48be37c66f79426e0a757a3e09816a4fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
